version: '3'
services:
  frontend:
    build: ./fron-tend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    volumes: 
      - ./back-end/src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.29
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

networks:
  default:
    name: app_net